import imgone from "../../../../assets/home/How it work/1st img.png";
import one from "../../../../assets/home/How it work/1.png"
import two from "../../../../assets/home/How it work/2.png"
import three from "../../../../assets/home/How it work/3.png"
import imgTwo from "../../../../assets/home/How it work/2nd img.png";
import imgThree from "../../../../assets/home/How it work/3rd png.png";
import "./style.css";
import line from "../../../../assets/Shared/line.png"


const HowItWork = () => {
  return (
    <div className="dark:bg-gray-800 dark:text-white">
      <div className="max-w-screen-xl mx-auto font-alice h-[100%] mt-[80px] hidden lg:block ">
        <h1 className="text-[38px] font-normal text-center  ">
          How It Work
        </h1>
        <img src={line} alt="" className="w-[105px] mx-auto mb-[30px]" />
        <p className="text-[18px]  font-lato text-center  max-w-[685px] mx-auto leading-[27px] mb-20">
          Create your profile, meet personalized matches, and <br /> build meaningful connections on your journey to love.
        </p>
        {/* cards */}
        <div className="">
          <div className="timeline " >
            <div>
              <div className="timeline__component">
                <div className="timeline__date flex justify-between " data-aos="fade-right" data-aos-duration="1500">
                  <img src={imgone} className="-mt-14 mb-16" alt="" />
                  <img src={one} className="h-[117px] hidden md:flex -mt-8" alt="" />
                </div>
              </div>
            </div>
            <div className="timeline__middle">
              <div className="timeline__point"></div>
            </div>
            <div className="-mt-6 p-[1.5em] " data-aos="fade-left" data-aos-duration="1500">
              <h1 className="text-[28px] font-normal leading-[36px] font-alice text-[#272932] mb-2 dark:text-white">
                Select based on Interests, Location, and other pertinent filters.
              </h1>
              <p className="text-[16px] font-normal text-[#3E4A5B] dark:text-white">
                Discover your life partner on our matrimonial website, where
                interests align and love blossoms. Tailored to your location and
                preferences, find meaningful connections that last a lifetime
              </p>
            </div>
            <div className="timeline__component timeline__component--bg " data-aos="fade-right" data-aos-duration="1500">
              <h1 className="text-[28px] font-normal leading-[36px] font-alice text-[#272932] text-right mb-2 -mt-6 dark:text-white">
                Engage with your matches in the manner that suits you best
              </h1>
              <p className="text-[16px] font-normal leading-[27px] text-[#3E4A5B] text-right dark:text-white">
                Communicate on your terms with potential matches on our matrimonial website, Matrimony. Whether it is through messages, chats, or video calls, forge genuine connections in a way that feels comfortable for you.
              </p>
            </div>

            <div className="timeline__middle">
              <div className="timeline__point"></div>
              <div className="timeline__point timeline__point--bottom"></div>
            </div>
            <div className="timeline__component">
              <div className="timeline__date flex justify-between " data-aos="fade-left" data-aos-duration="1500">
                <img src={two} className="h-[117px] hidden md:flex -mt-10" alt="" />
                <img src={imgTwo} className="-mt-14 mb-20" alt="" />
              </div>
            </div>
            <div className="timeline__component timeline__component--bottom flex justify-between" data-aos="fade-right" data-aos-duration="2000">
              <img src={imgThree} className="-mt-24 mb-12" alt="" />
              <img src={three} className="h-[117px] hidden md:flex -mt-16" alt="" />
            </div>
            <div className=" timeline__component--bottom timeline__component--bg">
              <div className="-mt-10 p-[1.5em]" data-aos="fade-left" data-aos-duration="2000">
                <h1 className="text-[28px] font-normal leading-[36px] font-alice text-[#272932] -mt-9 mb-2 dark:text-white">
                Personalized match suggestions generated by AI to align with your preferences
                </h1>
                <p className="text-[16px]  text-[#3E4A5B] dark:text-white">
                Communicate on your terms with potential matches on our matrimonial
                website, Matrimony. Whether it is through messages, chats, or video
                calls, forge genuine connections in a way that feels comfortable for
                you
                </p>
              </div>
            </div>
          </div>

        </div>

      </div>
      <div className=" lg:hidden w-[80%] mx-auto my-20">
        <div data-aos="fade-right" data-aos-duration="1500" className="justify-between gap-6 mb-5  md:flex items-center">
          <div className=" max-w-md mx-auto">
            <div className="cards_body">
              <img src={imgone} alt="" className="mb-10   " />
            </div>
          </div>
          {/* cards-2 */}
          <div className=" max-w-md mx-auto ">
            <div className="cards_body text-left">
              <h1 className="text-[20px] font-semibold leading-[36px]  text-[#272932] dark:text-white">
                Select based on Interests, Location, and other pertinent filters.
              </h1>
              <p className="text-[14px]  leading-[27px]">
                Discover your life partner on our matrimonial website, where
                interests align and love blossoms. Tailored to your location and
                preferences, find meaningful connections that last a lifetime
              </p>
            </div>
          </div>
        </div>

        {/* section-2 */}
        <div data-aos="fade-left" data-aos-duration="1500" className="md:flex sec  items-center justify-between gap-6 flex-row-reverse mb-5   ">
          {/* cards-3 */}
          <div className=" max-w-md mx-auto">
            <div className="cards_body">
              <img src={imgTwo} alt="" className="mb-10 " />
            </div>
          </div>
          {/* cards-4 */}
          <div className="max-w-md mx-auto">
            <div className="cards_body text-left md:text-right ">
              <h1 className="text-[28px] font-normal leading-[36px]  text-[#272932] dark:text-white">
                Engage with your matches in the manner that suits you best
              </h1>
              <p className="text-[18px] font-normal leading-[27px]">
                Discover your life partner on our matrimonial website, where
                interests align and love blossoms. Tailored to your location and
                preferences, find meaningful connections that last a lifetime
              </p>
            </div>
          </div>
        </div>
        {/* section-3 */}
        <div data-aos="fade-right" data-aos-duration="1500" className="md:flex sec items-center justify-between gap-6 mb-10  ">
          {/* cards-5 */}
          <div className=" max-w-md mx-auto ">
            <div className="cards_body">
              <img src={imgThree} alt="" className="mb-10  " />
            </div>
          </div>
          {/* cards-6 */}
          <div className="max-w-md mx-auto">
            <div className="cards_body text-left">
              <h1 className="text-[28px] font-normal leading-[36px]  text-[#272932] dark:text-white">
                Personalized match suggestions generated by AI to align with your
                preferences
              </h1>
              <p className="text-[18px] font-normal leading-[27px]">
                Communicate on your terms with potential matches on our matrimonial
                website, Matrimony. Whether it is through messages, chats, or video
                calls, forge genuine connections in a way that feels comfortable for
                you.
              </p>
            </div>
          </div>
          </div>
      </div>
    </div>
  );
};


export default HowItWork;



